import type { Metadata } from "next";
import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import { PageHero } from "@/components/PageHero";

export const metadata: Metadata = { title: "About — Growcode Solution", description: "The principles and operating model behind Growcode Solution." };
const values = [["01", "Clarity over theatre", "We make complex decisions visible, explain trade-offs, and communicate without performance."], ["02", "Quality is operational", "Quality comes from systems, reviews, observability, and ownership—not a final polish phase."], ["03", "Small senior teams", "The people in the room are the people doing the work. Expertise stays close to every decision."], ["04", "Outcomes before output", "More features are not the goal. Better customer and business outcomes are the measure."]];
const journey = [["Discover", "Frame the business constraint and the highest-leverage opportunity."], ["Define", "Align product, experience, architecture, and measurable success."], ["Deliver", "Ship in visible weekly increments with senior practitioners."], ["Evolve", "Measure real use, improve the system, and transfer durable capability."]];

export default function AboutPage() {
  return <main className="min-h-screen bg-[#080b12] text-white"><Navbar /><PageHero eyebrow="About / operating principles" title="Built for consequential work, not" accent="agency theatre." description="Northstar is a senior product studio for teams that need strategic clarity and production-grade execution in the same room." /><section className="px-4 py-24 sm:px-6"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><span className="section-label">Who we are</span><h2 className="section-title">A focused team of product thinkers and builders.</h2></div><div className="space-y-6 text-lg leading-8 text-slate-400"><p>We work at the intersection of product strategy, experience design, and software engineering. That combination lets us solve the whole problem instead of optimizing one handoff.</p><p>Our model is intentionally lean: senior people, direct communication, visible progress, and fewer layers between a decision and its implementation.</p></div></div></section><section className="border-y border-white/[0.08] bg-white/[0.025] px-4 py-24 sm:px-6"><div className="mx-auto max-w-7xl"><span className="section-label">What we stand for</span><div className="mt-10 grid gap-4 md:grid-cols-2">{values.map(([number, title, text]) => <article key={number} className="rounded-[1.75rem] border border-white/[0.09] bg-black/20 p-7 sm:p-8"><span className="font-mono text-xs text-brand-400">/{number}</span><h3 className="mt-8 text-2xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-slate-400">{text}</p></article>)}</div></div></section><section id="approach" className="px-4 py-24 sm:px-6"><div className="mx-auto max-w-7xl"><span className="section-label">How we work</span><h2 className="section-title">One accountable path<br />from intent to impact.</h2><div className="mt-12 grid gap-px overflow-hidden rounded-[2rem] border border-white/[0.09] bg-white/[0.09] md:grid-cols-4">{journey.map(([title, text], index) => <article key={title} className="bg-[#0d121d] p-7"><span className="font-mono text-xs text-brand-400">0{index + 1}</span><h3 className="mt-10 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{text}</p></article>)}</div></div></section><Footer /></main>;
}
