import type { Metadata } from "next";
import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import { PageHero } from "@/components/PageHero";

export const metadata: Metadata = { title: "Careers — Growcode Solution", description: "Join Growcode Solution and work on ambitious products with senior teams." };
const benefits = [["◈", "Deep work by default", "Protected focus time, thoughtful planning, and fewer performative meetings."], ["⌁", "Flexible location", "Work where you do your best work, with intentional overlap for collaboration."], ["↗", "Visible growth", "Clear expectations, senior mentorship, and an education budget you can actually use."], ["✦", "Meaningful products", "Work on systems where design and engineering materially change the business."]];
const roles = [{ title: "Senior Product Designer", type: "Full-time · Remote-friendly", skills: ["Product strategy", "Figma", "Design systems"] }, { title: "Senior Full-Stack Engineer", type: "Full-time · Remote-friendly", skills: ["Next.js", "TypeScript", "Node.js"] }, { title: "Flutter Engineer", type: "Contract / Full-time", skills: ["Flutter", "Mobile architecture", "APIs"] }];

export default function CareerPage() {
  return <main className="min-h-screen bg-[#080b12] text-white"><Navbar /><PageHero eyebrow="Careers / build with us" title="Do the strongest work of your career, with" accent="people who care." description="Join a small senior team solving product problems where craft, judgment, and engineering quality genuinely matter." /><section className="px-4 py-24 sm:px-6"><div className="mx-auto max-w-7xl"><span className="section-label">The environment</span><div className="mt-10 grid gap-4 md:grid-cols-2">{benefits.map(([icon, title, text]) => <article key={title} className="rounded-[1.75rem] border border-white/[0.09] bg-white/[0.04] p-7"><span className="text-2xl text-brand-300">{icon}</span><h2 className="mt-7 text-2xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-slate-400">{text}</p></article>)}</div></div></section><section className="border-y border-white/[0.08] bg-white/[0.025] px-4 py-24 sm:px-6"><div className="mx-auto max-w-5xl"><span className="section-label">Open roles</span><h2 className="section-title">Find your next challenge.</h2><div className="mt-10 space-y-4">{roles.map(role => <article key={role.title} className="group rounded-2xl border border-white/[0.09] bg-[#0d121d] p-6 transition hover:border-brand-400/25"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><h3 className="text-xl font-semibold">{role.title}</h3><p className="mt-1 text-sm text-slate-500">{role.type}</p><div className="mt-4 flex flex-wrap gap-2">{role.skills.map(skill => <span key={skill} className="rounded-full border border-white/10 px-3 py-1 text-xs text-slate-400">{skill}</span>)}</div></div><a href={`mailto:careers@northstar.digital?subject=${encodeURIComponent(`Application: ${role.title}`)}`} className="shrink-0 rounded-full bg-white px-5 py-2.5 text-center text-sm font-bold text-slate-950">Apply →</a></div></article>)}</div><p className="mt-8 text-center text-sm text-slate-500">Don’t see the right role? Send your work to <a className="text-brand-300" href="mailto:careers@northstar.digital">careers@northstar.digital</a>.</p></div></section><Footer /></main>;
}
